### PR TITLE
Fixes duplicate call of chooseLanguage when setting a language without subtag

### PR DESCRIPTION
**Pull request by LarsBauer**
Fixes a duplicate call of `chooseLanguage` when setting a language without subtag (e.g. "en"). To prevent the assignment of `currentLanguageTag` with non matching tag I added a missing return statement in the `setLanguage` method of numbro.

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
good catch!!

Could you add a test covering this case? That would prevent having the same issue later on :smile:

Also, please add yourself to the AUTHORS file :smile:

**Comment by LarsBauer** [comment]
Thank you for your quick response! 😄 

I added the missing test case. Eager to fix this issue I totally forgot to read your contributor guideline. Shame on me...

**Comment by BenjaminVanRyseghem** [comment]
No problem :smile:

**Comment by BenjaminVanRyseghem** [comment]
in v2.1.1

**Pull request merged**
