### PR TITLE
Use toFixed from BigNumber instead of Number

### LINKED ISSUE #570: mantissa precision produces wrong results for certain numbers
we have some cases where `mantissa: n` produces some wrong results. You can find an example here: https://numbrojs.com/try-me.html?lang=en-US&value=77896738.57&format=%7B%22trimMantissa%22%3Atrue%2C%22mantissa%22%3A8%7D

I would expect the result to be the input number in this case.

### PR DESCRIPTION
**Pull request by swissmanu**
Fixes #570

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
thanks for your fix! Could you please split your changes in 2 commits, so that the modification of AUTHORS is in its own commit? (this way, if your change get reverted, you will still be listed as an author :smile:)

Thanks in advance!

**Comment by swissmanu** [comment]
sure thing 👍 ✅

**Comment by BenjaminVanRyseghem** [comment]
@all-contributors please add @swissmanu for code

**Review by BenjaminVanRyseghem — APPROVED** [review]

**Comment by leabaertschi** [comment]
@BenjaminVanRyseghem any idea when this will be released? I would be interested in this fix as well

**Pull request merged**
