### PR TITLE
Update abbreviations in german language file

### PR DESCRIPTION
**Pull request by chaosflaws**
Currently, the German language file uses the English abbreviations for "million" and so on. This is particularly unhelpful because the names for large numbers do not match at all:

- million -> Million
- billion -> Milliarde
- trillion -> Billion

This exposes a bug in the unformatter's handling of byte-formatted numbers. In a string like `1Bi` (for one billion), the byte unformatter finds the capital B in the string and therefore treats this as bytes, which obviously isn't intended. I fixed this by making the unformatter search for complete postfixes without additional characters.

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Awesome!!! Thanks a lot :smile:

**Comment by BenjaminVanRyseghem** [comment]
let's wait for the CI now :smile:

**Comment by chaosflaws** [comment]
Oh wow! I only went to grab a coffee and wondered where my PR went... This must be the fastest merge I have seen so far :-D

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.3.3

**Pull request merged**
