### PR TITLE
Added support for Indian Number System (en-IN).

### PR DESCRIPTION
**Pull request by theY2Kbug**
- Added support for both Indian Number System (XX,XX,XXX) and Indian Currency (₹)
- Known bugs :  
    - ```state.currentLanguage = () => currentLanguageTag;``` (line - 56;  <i>globalState.js</i>) ocassionally throws an error saying its not a function  (I was unable to find a fix; To reproduce the error, console.log the error caught from the try-catch block in <i>formatting.js</i> (line - 668)
    -------
### Note: 
This is my very first open source contribution! Any suggestions, best practices and criticism is very much appreciated.

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Thanks a lot for your contribution. I had a very quick look, and it's promising :smile:

I'm a bit concerned about the bug you are describing, I'll try to take some time to dive into it.

Said being said, I have a rough week, and I'm not sure to be able to dedicate some time to it before this weekend at best

**Comment by theY2Kbug** [comment]
No worries. In the mean time, I'll see if I can find a fix for the bug and create an issue.

**Comment by theY2Kbug** [comment]
- Made minor optimizations to formatting.js
- Improved code readability

### Test status in local machine

```
SUCCESS: 464 specs, 0 failures, 0 skipped, 0 disabled in 6.343s.
------------------|----------|----------|----------|----------|----------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------|----------|----------|----------|----------|----------------|
 languages/       |      100 |      100 |      100 |      100 |                |
  bg.js           |      100 |      100 |      100 |      100 |                |
  cs-CZ.js        |      100 |      100 |      100 |      100 |                |
  da-DK.js        |      100 |      100 |      100 |      100 |                |
  de-AT.js        |      100 |      100 |      100 |      100 |                |
  de-CH.js        |      100 |      100 |      100 |      100 |                |
  de-DE.js        |      100 |      100 |      100 |      100 |                |
  de-LI.js        |      100 |      100 |      100 |      100 |                |
  el.js           |      100 |      100 |      100 |      100 |                |
  en-AU.js        |      100 |      100 |      100 |      100 |                |
  en-GB.js        |      100 |      100 |      100 |      100 |                |
  en-IE.js        |      100 |      100 |      100 |      100 |                |
  en-IN.js        |      100 |      100 |      100 |      100 |                |
  en-NZ.js        |      100 |      100 |      100 |      100 |                |
  en-ZA.js        |      100 |      100 |      100 |      100 |                |
  es-AR.js        |      100 |      100 |      100 |      100 |                |
  es-CL.js        |      100 |      100 |      100 |      100 |                |
  es-CO.js        |      100 |      100 |      100 |      100 |                |
  es-CR.js        |      100 |      100 |      100 |      100 |                |
  es-ES.js        |      100 |      100 |      100 |      100 |                |
  es-MX.js        |      100 |      100 |      100 |      100 |                |
  es-NI.js        |      100 |      100 |      100 |      100 |                |
  es-PE.js        |      100 |      100 |      100 |      100 |                |
  es-PR.js        |      100 |      100 |      100 |      100 |                |
  es-SV.js        |      100 |      100 |      100 |      100 |                |
  et-EE.js        |      100 |      100 |      100 |      100 |                |
  fa-IR.js        |      100 |      100 |      100 |      100 |                |
  fi-FI.js        |      100 |      100 |      100 |      100 |                |
  fil-PH.js       |      100 |      100 |      100 |      100 |                |
  fr-CA.js        |      100 |      100 |      100 |      100 |                |
  fr-CH.js        |      100 |      100 |      100 |      100 |                |
  fr-FR.js        |      100 |      100 |      100 |      100 |                |
  he-IL.js        |      100 |      100 |      100 |      100 |                |
  hu-HU.js        |      100 |      100 |      100 |      100 |                |
  id.js           |      100 |      100 |      100 |      100 |                |
  it-CH.js        |      100 |      100 |      100 |      100 |                |
  it-IT.js        |      100 |      100 |      100 |      100 |                |
  ja-JP.js        |      100 |      100 |      100 |      100 |                |
  ko-KR.js        |      100 |      100 |      100 |      100 |                |
  lv-LV.js        |      100 |      100 |      100 |      100 |                |
  nb-NO.js        |      100 |      100 |      100 |      100 |                |
  nb.js           |      100 |      100 |      100 |      100 |                |
  nl-BE.js        |      100 |      100 |      100 |      100 |                |
  nl-NL.js        |      100 |      100 |      100 |      100 |                |
  nn.js           |      100 |      100 |      100 |      100 |                |
  pl-PL.js        |      100 |      100 |      100 |      100 |                |
  pt-BR.js        |      100 |      100 |      100 |      100 |                |
  pt-PT.js        |      100 |      100 |      100 |      100 |                |
  ro-RO.js        |      100 |      100 |      100 |      100 |                |
  ro.js           |      100 |      100 |      100 |      100 |                |
  ru-RU.js        |      100 |      100 |      100 |      100 |                |
  ru-UA.js        |      100 |      100 |      100 |      100 |                |
  sk-SK.js        |      100 |      100 |      100 |      100 |                |
  sl.js           |      100 |      100 |      100 |      100 |                |
  sr-Cyrl-RS.js   |      100 |      100 |      100 |      100 |                |
  sv-SE.js        |      100 |      100 |      100 |      100 |                |
  th-TH.js        |      100 |      100 |      100 |      100 |                |
  tr-TR.js        |      100 |      100 |      100 |      100 |                |
  uk-UA.js        |      100 |      100 |      100 |      100 |                |
  zh-CN.js        |      100 |      100 |      100 |      100 |                |
  zh-MO.js        |      100 |      100 |      100 |      100 |                |
  zh-SG.js        |      100 |      100 |      100 |      100 |                |
  zh-TW.js        |      100 |      100 |      100 |      100 |                |
 src/             |      100 |      100 |      100 |      100 |                |
  en-US.js        |      100 |      100 |      100 |      100 |                |
  formatting.js   |      100 |      100 |      100 |      100 |                |
  globalState.js  |      100 |      100 |      100 |      100 |                |
  loading.js      |      100 |      100 |      100 |      100 |                |
  manipulating.js |      100 |      100 |      100 |      100 |                |
  numbro.js       |      100 |      100 |      100 |      100 |                |
  parsing.js      |      100 |      100 |      100 |      100 |                |
  unformatting.js |      100 |      100 |      100 |      100 |                |
  validating.js   |      100 |      100 |      100 |      100 |                |
------------------|----------|----------|----------|----------|----------------|
All files         |      100 |      100 |      100 |      100 |                |
------------------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 100% ( 962/962 )
Branches     : 100% ( 655/655 )
Functions    : 100% ( 115/115 )
Lines        : 100% ( 940/940 )
================================================================================
[21:34:04] Finished 'test:unit:run' after 7.42 s
[21:34:04] Finished 'test:unit' after 15 s
[21:34:08] Finished 'build:languages' after 5.08 s
[21:34:08] Starting 'build:write-languages'...
[21:34:08] Finished 'build:languages' after 5.16 s
[21:34:08] Starting 'build:write-languages'...
[21:34:10] Finished 'build:write-languages' after 2.74 s
[21:34:10] Finished 'build:all-languages' after 7.82 s
[21:34:10] Finished 'build' after 22 s
[21:34:10] Finished 'test:integration:node' after 22 s
[21:34:13] Finished 'build:write-languages' after 5.46 s
[21:34:13] Finished 'build:all-languages' after 11 s
[21:34:13] Finished 'build' after 25 s
[21:34:13] Finished 'test:integration:amd' after 25 s
[21:34:13] Finished 'test:integration' after 25 s
[21:34:13] Finished 'test' after 25 s
[21:34:13] Finished 'test' after 25 s
```

**Comment by theY2Kbug** [comment]
@BenjaminVanRyseghem 

I was still unable to find the root cause of the issue. The attached screenshot was captured during testing. 

Since I made certain changes to support the Indian Number System during which I caught this bug, do you want me to open an issue before the approval of this PR or should I open it post the approval?

Screenshot from 2022-06-23 10-39-31

**Comment by theY2Kbug** [comment]
@BenjaminVanRyseghem, Just dropping a gentle reminder, I am still awaiting a workflow approval, if something is seems off... do let me know

**Comment by theY2Kbug** [comment]
@BenjaminVanRyseghem, Now that all checks have passed, what is a realistic time frame for the merge of this PR and release of v2.3.7 with en-IN support? 

I'm eagerly waiting to use the formatting feature in my new project!

**Comment by theY2Kbug** [comment]
@BenjaminVanRyseghem, I just noticed that I forgot to create a new branch and pushed everything to 'develop'. Is it all right or do you want me to close this PR, create a new branch and a new PR?

**Comment by theY2Kbug** [comment]
I'm closing this PR. I'm creating a new one with just one single commit and a new branch

**Pull request closed without merging**
