### PR TITLE
Fix currencySymbol return type in TS definition of Format interface.

### PR DESCRIPTION
**Pull request by jarnovanleeuwen**
Should be typehinted as type `string` type and not string `"string"`.

### CODE REVIEW

**Comment by kravemir** [comment]
@BenjaminVanRyseghem can you please merge this fix?

**Comment by BenjaminVanRyseghem** [comment]
@jarnovanleeuwen  thanks for your contribution

Could you please add yourself to the AUTHORS.md file and add a line in CHANGELOG.md?

Thanks again

**Comment by jarnovanleeuwen** [comment]
No problem! Done, and thanks in advance for merging.

**Comment by BenjaminVanRyseghem** [comment]
@all-contributors please add @jarnovanleeuwen for code

**Comment by pbasista** [comment]
Hi @BenjaminVanRyseghem, could you release a new patch version with this change?

**Pull request merged**
