### PR TITLE
fixed currency position for nl-NL

### PR DESCRIPTION
**Pull request by jordydejong**
for locale nl-NL, I think the currency symbol should come before the value

the browser's Internationalization API seems to agree

```
Intl.NumberFormat(‘nl-NL’, {style: ‘currency’, currency: ‘EUR’}).format(123.567)
```

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Could you fix tests as well?

**Comment by jordydejong** [comment]
sure, sorry about that

**Comment by BenjaminVanRyseghem** [comment]
Could you squash your commits and add yourself in the AUTHORS file? 😄 

Your PR looks good otherwise 👍

**Comment by BenjaminVanRyseghem** [comment]
why closing it?

**Pull request closed without merging**
