### PR TITLE
Fix formatCurrency when value > 0 and forceSign

### LINKED ISSUE #418: formatCurrency - forceSign doesn't work properly when number is positive
```
numbro(1000).formatCurrency({forceSign: true}) -> $+1000
numbro(-1000).formatCurrency({forceSign: true}) -> -$1000
```
I would expect the first one to be +$1000

### PR DESCRIPTION
**Pull request by adriang133**
Fixes #418

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Thanks for the PR, and sorry for the delay.

Could you please add yourself to the AUTHOR file as well as a line in CHANGELOG?

Thanks in advance

**Comment by BenjaminVanRyseghem** [comment]
The PR cannot be merged. Could you have a look please ?

**Comment by adriang133** [comment]
Fixed now, thanks for taking a look!

**Comment by BenjaminVanRyseghem** [comment]
"This branch cannot be rebased due to conflicts" 

sorry.

Do you want me to have a look ?

**Comment by adriang133** [comment]
Sorry, early in the morning 😄  I rebased on develop, it should be fine now ?

**Comment by BenjaminVanRyseghem** [comment]
Perfect thanks!

**Pull request merged**
