### PR TITLE
align typescript interface with validation properties

### PR DESCRIPTION
**Pull request by cornflakeboy**
Hey,
I'd like to use numbro with typescript and noticed your numbro.d.ts interfaces are missing two properties stated in the validating file.

Could you please add them?

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
First, thanks for the PR :smile:

The AUTHORS file is conflicting, my bad for the delay 😕 

Could you please update it? Then I'll merge your PR

**Comment by cornflakeboy** [comment]
I´ve updated the authors file and additionaly defined the property thousandsSize to be optional in the typescript interface because I noticed that many language definitions don't use it.

**Comment by BenjaminVanRyseghem** [comment]
@cornflakeboy I still can't rebase it...

>Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Comment by cornflakeboy** [comment]
Sorry, I didn't realize there was a rebase conflict and locally checked for conflicts using merge. Created PR #533 to not have like 5 commits for these 4 lines of code :)
feel free to reject this one...

**Pull request closed without merging**
