### PR TITLE
Fixes #372

### LINKED ISSUE #372: mantissa: 0 and trimMantissa: true results in truncated numbers
image

https://runkit.com/timfish/5b7c70e7466e950012e31356

### PR DESCRIPTION
**Pull request by timfish**
Fixes #372

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Hey! Thanks for the contribution!

Could you please:
- squash your commits
- add yourself to the AUTHOR list
- (maybe add an entry in the CHANGELOG)

Thanks in advance!

**Comment by timfish** [comment]
I'm lazy. I normally just let Github squash my commits:

image

**Comment by BenjaminVanRyseghem** [comment]
I know this option, but I would like to keep the "code" commit apart from the "Author + Changelog" commit (reverting one day your code should not revert the changelog nor the fact that your are a contributor :smile:)

**Comment by timfish** [comment]
Ahhh ok, fair enough. I will attempt this!

**Comment by BenjaminVanRyseghem** [comment]
```
git reset --hard 70a9727
git reset --soft HEAD~
git commit --amend
git cherry-pick 7097f5c
git push --force-with-lease
```

should do :smile:

**Comment by timfish** [comment]
It's far too late and I've had too much wine to be messing around with git!

**Comment by timfish** [comment]
Sorry, I thought I had finished this!

**Comment by timfish** [comment]
@BenjaminVanRyseghem any chance of getting this in?

**Comment by BenjaminVanRyseghem** [comment]
done :smile:

I'll do a release ASAP

**Comment by BenjaminVanRyseghem** [comment]
in v2.1.1

**Pull request merged**
