### PR TITLE
Add ordinal for 40 for tr-TR

### PR DESCRIPTION
**Pull request by yatki**
ordinal for 40 was missing. Now should be fine :) 🖖

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Thank you :smile:

Could you please add yourself to the AUTHOR file, as well as a line in the CHANGELOG?

Thanks in advance :smile:

**Comment by yatki** [comment]
@BenjaminVanRyseghem addressed :)

**Comment by BenjaminVanRyseghem** [comment]
It looks like you changed the CHANGELOG wayyyy to much :smile:

I suspect a md IDE to have gone bananas 😛

**Comment by yatki** [comment]
@BenjaminVanRyseghem Oops 😄  Fixed 🖖

**Comment by BenjaminVanRyseghem** [comment]
Thanks!

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.2.0

**Pull request merged**
