### PR TITLE
Fix currencySymbol string literal type

### PR DESCRIPTION
**Pull request by babangsund**
The type for `currencySymbol` is currently a string literal -`"string"`, instead of `string` (e.g. to be used as "$", or "¥").

- Fix a typings issue
- Update changelog
- Add author

### CODE REVIEW

**Comment by babangsund** [comment]
I just noticed this is a duplicate of [this pr](https://github.com/BenjaminVanRyseghem/numbro/pull/470), but I'll keep mine around, since it confines to the contribution guidelines.

**Comment by tostavio** [comment]
Today I had same problem. I was going to open pr, but you've already opened. Thanks.

**Comment by kravemir** [comment]
Fixed in #470.

**Comment by BenjaminVanRyseghem** [comment]
@babangsund is it safe to close then?

**Pull request closed without merging**
