### PR TITLE
Make it possible to add space between abbreviation and postfix currency #577

### PR DESCRIPTION
**Pull request by marvec**

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Thanks!!!

Just a little fix: could you please rearrange your commits as follow please?
- one commit with all the code + changelog
- one commit with AUTHORS (so that potentially reverting your code commit won't remove you from the contributors list :smile:)

Thanks in advance

**Comment by BenjaminVanRyseghem** [comment]
@all-contributors please add @marvec  for bug, code

**Comment by marvec** [comment]
@BenjaminVanRyseghem Thank you for your quick reaction to this PR. I hope I managed to put it in the right shape. Do you have any estimates on when this could make its way to a release?

**Comment by marvec** [comment]
Hello @BenjaminVanRyseghem, I understand that you probably have other ton of work and I appreciate your time invested in this awesome project. However, we are sort of dependent on this fix. I would like to figure out whether it is worth waiting for a next numbro release, or we should invest the time and fork it temporarily... Many thanks!

**Comment by BenjaminVanRyseghem** [comment]
@marvec I understand, and I am sorry I can't be faster. I'll try to release somehow tonight after I put the kids to bed.

In the meantime, you can always have npm point to a github sha and avoid a fork

**Comment by marvec** [comment]
Thank you very much! We really appreciate your help. I did not know about the ability to point to a github sha. Thank you for extending my knowledge!

**Comment by marvec** [comment]
Just letting you know - sha does not work - there are missing files that get created with the build (language.min.js for example). So no luck :-(

**Comment by BenjaminVanRyseghem** [comment]
@marvec I'm sorry 😞 I'll try to release it asap, and I will try so setup a built-branch so that someone can pick a sha

**Pull request merged**
