### PR TITLE
Correct broken BCP47 link

### PR DESCRIPTION
**Pull request by sesam**

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
Hi!

Thanks for the PR :)

Could you please add yourself to the AUTHORS file, as well as add a line in the CHANGELOG?

Thanks in advance,
Benjamin Van Ryseghem

**Comment by BenjaminVanRyseghem** [comment]
It looks like your `develop` branch was not up to date :smile:

Also, could you squash all your commits into a single one?

Thanks in advance :smile:

**Comment by BenjaminVanRyseghem** [comment]
Thanks a lot!!

**Comment by sesam** [comment]
Sure, no worries.

Github for open source has some issues, but I probably shoulr use the github command line tool or something, since git by itself doesn't seem to allow me to *track* one branch but push updates to another origin and another branch.

There likely is some good PR-tool layered on top of plumbing, just I don't know which. Gerrit and GitKraken didn't convince me. I like command line tools and rebase -i. Otherwise `gitup` is by current best bet for managing messy branch/merge issues and splitting + rearranging commits

**Comment by BenjaminVanRyseghem** [comment]
>  since git by itself doesn't seem to allow me to track one branch but push updates to another origin and another branch.

I am not sure to understand :smile:

**Comment by sesam** [comment]
Thanks, I'm just looking for new knowledge on using github effectively for open source.

But I made one more try, with a "hack" in my local `.git/config` file. Trying to hack command line `git` into allowing me to base (and have `git pull --rebase`) use upstream = the software maintainer's repository, but still have `git push` send commits to my own where I have write access.
This maybe works at least partially:
https://www.dropbox.com/s/kh2dvdsdugolm97/Screenshot%202019-12-13%2013.38.03.png?dl=0

But I expect this to break something somewhere. Will see when next change on develop is merged, if I learnt something new or just created more work for myself (and any readers).

Anyway, have a nice day!

**Comment by BenjaminVanRyseghem** [comment]
`
git remote add pr git@github.com:BenjaminVanRyseghem/numbro.git
git fetch pr
git checkout develop
git rebase pr/develop
git push --force-with-lease origin/develop
`

something like that might do, or ?

**Comment by BenjaminVanRyseghem** [comment]
in numbro 2.2.0

**Pull request merged**
